### CHECK HEALTH
GET {{host}}
Content-Type: application/json

### V1 HEALTH 
GET {{host}}/v1
Content-Type: application/json

### V1 AUTH/REGISTER
POST {{host}}/v1/auth/register
Content-Type: application/json

{
    "firstName": "Jokowo",
    "lastName": "Prabowi",
    "email": "example3@mail.com",
    "password": "password",
    "passwordConfirmation": "password"
}

### V1 AUTH/LOGIN
POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "email": "example1@mail.com",
    "password": "password"
}

### V1 AUTH/ME
GET {{host}}/v1/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZW1haWwiOiJleGFtcGxlMUBtYWlsLmNvbSIsImlhdCI6MTcwMTQzNzczMywiZXhwIjoxNzAxNDM4MzMzfQ.9LsrYMwMHAV3BgNCswXmKihgMIMJ699N2CeJUvTYP6Y