
version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - '${SERVICE_API_GATEWAY_PORT:-80}:80'
    volumes:
      - .:/app
    networks:
      - linkdlaw
    depends_on:
      - db
      - cache

  db:
    image: postgres:13.12
    environment:
      POSTGRES_USER: '${DB_USER:-lawdlink_user}:lawdlink_user'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}:password'
      POSTGRES_DB: '${DB_NAME:-lawdlink_db}:lawdlink_db'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - lawdlink_db:/var/lib/postgresql/data
    networks:
      - linkdlaw

  cache:
    image: redis:7.2.3
    ports:
      - '${CACHE_PORT:-6379}:6379'
    networks:
      - linkdlaw

volumes:
  lawdlink_db:
    driver: local

networks:
  linkdlaw:
    driver: bridge
