### V1 AUTH/ME
GET {{host}}/v1/test?a=t
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZW1haWwiOiJleGFtcGxlMUBtYWlsLmNvbSIsImlhdCI6MTcwMTg0NTUxOCwiZXhwIjoxNzAxODQ2MTE4fQ.0hKc4fI8qvAeUlL1toz7IcADbosA7Equ35V25AVBcXg

### V1
GET {{host}}/hello