name: CD

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "Hello World from Continuous Deployment!"
  
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      # - name: Build the Docker image
      #   run: docker build ./docker/dev --file Dockerfile --tag linkdlaw:$(date +%s)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: nakamacapstone/linkdlaw
          workdir: ./docker/dev
          dockerfile: Dockerfile
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  apps-mobile-android-build-release-apk:
    name: (apps/mobile-android) Generate Production Release Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Build Production APK
        run: ./gradlew assembleRelease
        working-directory: ./apps/mobile-android
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-release-unsigned.apk
          path: apps/mobile-android/app/build/outputs/apk/release/app-release-unsigned.apk
