name: CI

on:
  push:
    branches:
      - main
    # branches:
    #   - '!main'
    pull_request:
      branches:
        - main

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install dependencies
        run: bun install
      - name: run tests
        run: bun test
      - name: lint
        run: bun lint
