name: CI

on:
  push:
    branches:
      - dev
      - dev/cc
      - dev/md
      - dev/ml
      # - '!main'
  pull_request:
    branches:
      - main
      - dev

jobs:
  api-lint:
    name: (api) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install dependencies
        run: bun install
      - name: run tests
        run: bun test
      - name: lint
        run: bun lint

  apps-mobile-android-lint:
    name: (apps/mobile-android) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Run lint
        run: ./gradlew lintDebug
        working-directory: ./apps/mobile-android
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint-results-debug.html
          path: apps/mobile-android/app/build/reports/lint-results-debug.html

  apps-mobile-android-debug-apk:
    name: (apps/mobile-android) Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        working-directory: ./apps/mobile-android
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-debug.apk
          path: apps/mobile-android/app/build/outputs/apk/debug/app-debug.apk
  
  artifacts-comment:
    name: Generate artifacts and comment on PR
    runs-on: ubuntu-latest
    needs: [apps-mobile-android-lint, apps-mobile-android-debug-apk]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Download artifacts - debug APK
        uses: actions/download-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-debug.apk
      - name: Download artifacts - lint report
        uses: actions/download-artifact@v2
        with:
          name: lint-results-debug.html
      - name: Display structure of the artifacts directory
        run: ls -R
      - name: Renaming artifacts file
        run: |
          mv app-debug.apk com.nakama.capstone.linkdlaw-debug.apk
      - name: Pull request artifacts
        if: github.event_name == 'pull_request'
        uses: gavv/pull-request-artifacts@v2
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          inter-link: false
          artifacts-branch: artifacts
          artifacts: |
            com.nakama.capstone.linkdlaw-debug.apk
            lint-results-debug.html