name: CI

on:
  push:
    branches:
      - main
    # branches:
    #   - '!main'
  pull_request:
    branches:
      - main

jobs:
  api-lint:
    name: (api) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install dependencies
        run: bun install
      - name: run tests
        run: bun test
      - name: lint
        run: bun lint

  apps-mobile-lint:
    name: (apps/mobile-android) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Run lint
        run: ./gradlew lintDebug
        working-directory: ./apps/mobile-android
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: apps/mobile-android/app/build/reports/lint-results-debug.html

  apps-mobile-unit-test:
    name: (apps/mobile-android) Perform Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./apps/mobile-android/gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: apps/mobile-android/app/build/reports/test/testDebugUnitTest/

  apps-mobile-debug-apk:
    name: (apps/mobile-android) Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build debug APK
        run: ./apps/mobile-android/gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: sample-app.apk
          path: apps/mobile-android/app/build/outputs/apk/debug/app-debug.apk