name: CI

on:
  push:
    branches:
      - dev
      - dev-cc
      - dev-md
      - dev-ml
      # - '!main'
  pull_request:
    branches:
      - main
      - dev

jobs:
  api-lint:
    name: (api) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install dependencies
        run: bun install
      - name: lint
        run: bun lint

  # api-tests:
  #   name: (api) Perform tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #     - name: setup bun
  #       uses: oven-sh/setup-bun@v1
  #     - name: install dependencies
  #       run: bun install
  #     - name: run tests
  #       run: bun test

  apps-mobile-android-lint:
    name: (apps/mobile-android) Perform lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Run lint
        run: ./gradlew lintDebug
        working-directory: ./apps/mobile-android
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint-results-debug.html
          path: apps/mobile-android/app/build/reports/lint-results-debug.html

  apps-mobile-android-build-debug-apk:
    name: (apps/mobile-android) Generate Debug Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        working-directory: ./apps/mobile-android
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-debug.apk
          path: apps/mobile-android/app/build/outputs/apk/debug/app-debug.apk
  
  apps-mobile-android-build-release-apk:
    name: (apps/mobile-android) Generate Production Release Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
        working-directory: ./apps/mobile-android
      - name: Build Production APK
        run: ./gradlew assembleRelease
        working-directory: ./apps/mobile-android
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-release-unsigned.apk
          path: apps/mobile-android/app/build/outputs/apk/release/app-release-unsigned.apk

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: nakamacapstone/linkdlaw
          dockerfile: ./docker/dev/Dockerfile
          tags: latest-dev-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  build-openapi-redocly:
    name: Build OpenAPI with Redocly
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      deploymentUrl: ${{ steps.deploy.outputs.deploymentUrl }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install dependencies
        run: bun i
      - name: install vercel
        run: bun i -g vercel @redocly/cli
      - name: build openapi
        run: bun run build:openapi
      - name: list files
        run: |
          ls && ls -R ./dist
      - name: archive openapi
        uses: actions/upload-artifact@v2
        with:
          name: link-d-law-openapi.html
          path: ./dist/openapi-doc/index.html
      - name: Deploy redoc build to Vercel
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --cwd=./dist/openapi-doc
      - name: Build with Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --cwd=./dist/openapi-doc
      - id: deploy
        name: Deploy to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd=./dist/openapi-doc > deploy.log
          URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
          echo "deploymentUrl=$URL" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
      - name: Comment URL to PR
        uses: actions/github-script@v6
        if : github.event_name == 'pull_request'
        id: comment-deployment-url-script
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deploymentUrl }}
        with:
          script: |
            // Get pull requests that are open for current ref.
            const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })

            // Set issue number for following calls from context (if on pull request event) or from above variable.
            const issueNumber = context.issue.number || pullRequests.data[0].number

            // Retrieve existing bot comments for the PR
            const {data: comments} = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
            })
            const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes('OPENAPI Docs Deploy at')
            })

            const output = `OPENAPI Docs Deploy at : ${process.env.DEPLOYMENT_URL}\n\n_Deployed at: ${new Date().toUTCString()}_`

            // If we have a comment, update it, otherwise create a new one
            if (botComment) {
                github.rest.issues.updateComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: botComment.id,
                    body: output
                })
            } else {
                github.rest.issues.createComment({
                    issue_number: issueNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                })
            }

  artifacts-comment:
    name: Generate artifacts and comment on PR
    runs-on: ubuntu-latest
    needs: [apps-mobile-android-lint, apps-mobile-android-build-debug-apk, apps-mobile-android-build-release-apk]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Download artifacts - debug APK
        uses: actions/download-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-debug.apk
      - name: Download artifacts - release APK
        uses: actions/download-artifact@v2
        with:
          name: com.nakama.capstone.linkdlaw-release-unsigned.apk
      - name: Download artifacts - lint report
        uses: actions/download-artifact@v2
        with:
          name: lint-results-debug.html
      - name: Display structure of the artifacts directory
        run: ls -R
      - name: Renaming artifacts file
        run: |
          mv app-debug.apk com.nakama.capstone.linkdlaw-debug.apk
          mv app-release-unsigned.apk com.nakama.capstone.linkdlaw-release-unsigned.apk
      - name: Pull request artifacts
        if: github.event_name == 'pull_request'
        uses: gavv/pull-request-artifacts@v2
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          inter-link: false
          # artifacts-branch: artifacts
          artifacts-repo: link-d-law-artifacts
          artifacts-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            com.nakama.capstone.linkdlaw-debug.apk
            com.nakama.capstone.linkdlaw-release-unsigned.apk
            lint-results-debug.html
